version: '3.8'

services:
  # PHP-FPM service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsaggregator-php
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    depends_on:
     - db
    networks:
      - newsaggregator-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: newsaggregator-nginx
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - newsaggregator-network

  # PostgreSQL service
  db:
    image: postgres:16
    container_name: newsaggregator-db
    environment:
      POSTGRES_USER: agwenchez
      POSTGRES_PASSWORD: Agwenchez254
      POSTGRES_DB: newsaggregator
    volumes:
      - ./docker-compose/postgres:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - newsaggregator-network

volumes:
  pgdata:

networks:
  newsaggregator-network:
    driver: bridge
